# docker-compose.yml
version: '3'

networks:
  db-data-net:
    driver: bridge

services:
  
  pythonapp:
    image: app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db-data-net
    environment:
      - DB_HOST=mysql
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=1234
    depends_on:
      - mysql
    restart: unless-stopped  
  
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net

volumes:
  db-data:
